# -*- coding: utf-8 -*-
"""While Loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vVmS5BAwoEXfGB9cGA8l7yEFH5GR9N3v
"""

print("while loop")

i = 1
while i <= 10:
  print(i)
  i = i+1

i = 10
while i >= 1:
  print(i)
  i -= 1

i = 2
while i <= 20:
  if i%2 == 0:
    print(i)
  i += 1

i = 1
while i <= 20:
    print(i)
    i += 2

password = "usman"

while True:
  n = input()
  if n == password:
    print("Access granted")
    break
  else:
    print("Try again")

password = "usman"
attemp =0
max_attemp =3
while attemp < max_attemp:
  n = input()
  if n == password:
    print("Access granted")
    break
  else:
    print("Try again")
    attemp+=1

if attemp == max_attemp:
  print("Account is blocked")

while True:
  print("Enter the positive number")
  number = int(input())

  if number > 0:
    print("Entered number is:  ", number)
  else:
    print("Invalid number")
    break

i = 0
sum = 0
while i < 5:
  n = int(input("enter the number: "))
  sum += n
  i+=1

print(sum)

i = 1
n = int(input("Enter the table number: "))
while i <= 10:

  print(n , " * ", i, " = ", n*i )
  i+=1

i = 0
while i < 5:
  j = 0
  while j<=i:
    print("*", end="" )
    j+=1
  print()
  i+=1

i = 4
while i >= 0:
  j = 0
  while j<=i:
    print("*", end="" )
    j+=1
  print()
  i-=1

while True:
  print("1. Start Game")
  print("2. Setting")
  print("3. Exit")
  n = int(input("Enter your option: "))
  if (n ==1 or n==2):
    print("Feature coming soon")
  else:
    break

num_rows = 5 # You can change this value to control the number of rows
i = 0
while i < num_rows:
  j = 0
  while j<=i:
    print("*", end="" )
    j+=1
  print()
  i+=1

import random
guess = random.randint(1,20)
attemp = 1
while True:

  n = int(input("Enter the number: "))


  if n > guess:
    print("too high")

  elif n < guess:
    print("too low")
  else:
    print("You won")
    print(f"You won in {attemp} attemps")
    break
  attemp +=1

print("C:", "Users", "Usman", sep="\\")
a ,b, c = 2, 3,  4
print(a, b, c, sep=" BETWEEN ", end=" AFTER")

i=1
while i<=6:
  j = 1
  while j < i:
    print(j, end="")
    j+=1
  print()
  i+=1

i=0
while i<=5:
  j = 0
  while j < i:
    print(i, end="")
    j+=1
  print()
  i+=1

i=5
while i>0:
  j = 5
  while j >= i:
    print(i, end="")
    j-=1
  print()
  i-=1

i = 1
while i <=5:
  j = 5
  while i<=j:
    print(j, end="")
    j-=1
  print()
  i+=1

i = 5
while i >= 1:
    j = 1
    while j <= i:
        print(j, end="")
        j += 1
    print()
    i -= 1

i = 5
while i >= 1:
    j = 1
    while j <= i:
        print(i, end="")
        j += 1
    print()
    i -= 1

i=1
k =1
while i<=4:
  j = 0

  while j < i:

    print(k, end="")
    j+=1
    k+=1
  print()
  i+=1

i=1
k =10
while i<=4:
  j = 0

  while j < i:

    print(k, end="")
    j+=1
    k-=1
  print()
  i+=1